# Generated by Django 4.1.1 on 2022-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories_products_pimanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.CharField(max_length=25),
        ),
    ]
