# Generated by Django 4.1.1 on 2022-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shops_shopitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='total',
            field=models.FloatField(),
        ),
    ]
