# Generated by Django 4.1.1 on 2022-09-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_products_discount_alter_products_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_item', to='main.products'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_item', to='main.shops'),
        ),
    ]
