# Generated by Django 4.1.1 on 2022-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_shopitems_product_alter_shopitems_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
