# Generated by Django 4.1.1 on 2022-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_shops_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('booked', 'booked'), ('canceled', 'canceled'), ('accepted', 'accepted'), ('sent', 'sent'), ('sold', 'sold'), ('paid', 'paid')], default='opened', max_length=10),
        ),
    ]
